package planograma.constant;

/**
 * User: a_polyakov
 */
public enum OptionsNameConst {
	RACK_TEMPLATE_SAVE_DIMENSION,
	RACK_TEMPLATE_SAVE_SHELF_DIMENSION,
	RACK_TEMPLATE_SAVE_SHELF_OUT_OF_RACK,

	SECTOR_SAVE_DIMENSION,
	SECTOR_SAVE_RACK_DIMENSION,
	SECTOR_SAVE_RACK_OUT_OF_SECTOR,
	SECTOR_SAVE_RACK_INTERSECTION,
	SECTOR_SAVE_RACK_SHELF_DIMENSION,
	SECTOR_SAVE_RACK_REAL_DIMENSION_LESS_THEN_WARES,

	RACK_SAVE_DIMENSION,
	RACK_SAVE_SHELF_DIMENSION,
	RACK_SAVE_SHELF_OUT_OF_RACK,
	RACK_SAVE_RACK_REAL_DIMENSION_LESS_THEN_WARES,
	RACK_SAVE_SHELF_INTERSECT_WARES,
	RACK_SAVE_RACK_OUT_SECTOR,
	RACK_SAVE_RACK_INTERSECTION,

	WARES_SAVE_WARES_IN_REAL_DIMENSION,
	WARES_SAVE_WARES_INSTERSECT_SHELF,
	WARES_SAVE_WARES_INTERSECT_WARES,
	WARES_SAVE_SHELF_DIMENSION,
	WARES_SAVE_SHELF_OUT_OF_RACK;
}
